# Generated by Django 5.2 on 2025-04-26 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], default='email', max_length=20)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('otp_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='OAuthSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], default='google', max_length=20)),
                ('encrypted_refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_sessions', to='account.account')),
            ],
            options={
                'verbose_name': 'OAuth Session',
                'verbose_name_plural': 'OAuth Sessions',
                'db_table': 'oauth_sessions',
            },
        ),
    ]
