# Generated by Django 5.2 on 2025-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='major',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
