# Generated by Django 5.2 on 2025-05-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_adminprofile_kompanyprofile_kreatorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
