# Generated by Django 5.2 on 2025-05-10 02:27

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('gist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gist_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('avitag', models.CharField(max_length=255)),
                ('is_reported', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('gist', 'Gist'), ('event', 'Event')], max_length=10)),
                ('entity_id', models.UUIDField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avitag', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('commented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gist.gist')),
            ],
            options={
                'ordering': ['commented_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avitag', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('GIST', 'Gist'), ('COMMENT', 'Comment')], max_length=10)),
                ('entity_id', models.UUIDField()),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('FIRE', 'Fire'), ('SAD', 'Sad'), ('WOW', 'Wow')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('avitag', 'entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_by', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACTION_TAKEN', 'Action Taken'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gist.gist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avi_tag', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='gist.gist')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('gist', 'avi_tag')},
            },
        ),
    ]
